version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
  server:
    build: ./apps/server
    restart: unless-stopped
    depends_on: [mongo]
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/enagram
    env_file: ./apps/server/.env
    ports:
      - '4000:4000'
    volumes:
      - uploads:/app/uploads
volumes:
  mongo_data:
  uploads:
